// Declare and initialize variables
let selectedNumber = 0; //variable to store number selected by user
let sum = 0;            //variable to store sum of user input and random number
let rndsum = 0;         //variable to store total of random numbers generated
let usersum = 0;        //variable to store total of user selected numbers
let gameEnded = false;  //variable to track if the game ended

// Function to add user input and random number to the sum
function add(userInput, sum, randNum) {
  sum = sum + userInput + randNum;
  console.log(sum); //console the sum for debugging purpose
  return sum;
}

//Function to enable or disable number buttons based on game status
function setNumberButtonsState(enabled){
  document.querySelectorAll(`.numberbutton`).forEach(button => {
    button.disabled = !enabled;
  })
}


// Event listeners for number buttons
document.querySelectorAll('.numberbutton').forEach(button => {
  button.addEventListener('click', function () {
    if(!gameEnded){
      // Update and display the selected number
      selectedNumber = parseInt(this.dataset.value);
      document.getElementById('result').style.whiteSpace = 'pre-line'; // referred chatGPT
      document.getElementById('result').textContent = `You have selected: ${selectedNumber} `;
    
      // Generate a random number
      const randNum = Math.round(Math.random() * 5) + 1;
      console.log(randNum); // console the randnum for debugging purpose
    
      // Update game variables and check game status
      sum = add(selectedNumber, sum, randNum);//calling the function add and passing the parameters
      usersum = usersum + selectedNumber;     // Adding the numbers selected by the user and storing in the variable usersum
      rndsum = rndsum + randNum;              //Adding the numbers generated by the computer and storing in the variable rndsum
      document.getElementById('result').textContent += `\nThe current running total is: ${sum}`;
      //checking whether the user won the game, lost or still playing and sending the corresponding message to the display area
      if (sum === 21) {
        document.getElementById('result').textContent += `\nEnd of the Game!\n\nCongratulations! You won! 🏆😊`;             
      } else if (sum > 21) {
        document.getElementById('result').textContent += `\nEnd of the Game!\n\nSorry, you lost the game💔😢. Better luck next time!`;        
      } else {
        document.getElementById('result').textContent += '\nYou are still under 21. Keep Playing!';
      }
      //checking if the game ended with win or lost,displaying scores and resetting variables for new game
      if (sum === 21 || sum > 21) {
        // Display the final scores and reset the game
          document.getElementById('result').textContent += `\nThe Game Total is:  ${sum}`
          document.getElementById('result').textContent += `\nYour Final Score is:  ${usersum}`
          document.getElementById('result').textContent += `\nDealer's Final Score is:  ${rndsum}`
          document.getElementById('replayButton').style.display = 'block';//show the playAgain button - referred chatGPT
          sum = 0;  // reset the game total variable
          rndsum = 0; // reset the computer total variable
          usersum = 0; // reset the player total variable
          gameEnded = true; // changing the game status as ended
          setNumberButtonsState(false); // disabling the buttons
      }
    
    }
  });
});

// Event listener for replay button
document.getElementById('replayButton').addEventListener('click', function () { 
  // Reset the game and clear the result 
  document.getElementById('result').textContent = '';
  selectedNumber = 0; // reset selected variable
  sum = 0;            //reset the game total variable
  document.getElementById('replayButton').style.display = 'none'; // when the game restarts hide the replay button - referred chatGPT
  gameEnded =false; //Set the game status to begin (not ended)
  setNumberButtonsState(true); // Enable the number buttons
});
